apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-data
  labels:
    app: sonar
  annotations:
    volume.beta.kubernetes.io/storage-class: "openebs-cstor-disk"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
