apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sonar
  name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonar
  template:
    metadata:
      labels:
        app: sonar
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:8.3-community
          volumeMounts:
          - mountPath: /opt/sonarqube/data/
            name: sonar-data
          - mountPath: /opt/sonarqube/extensions/
            name: sonar-extensions
          env:
          - name: SONARQUBE_JDBC_USERNAME
            value: {jdbc_username}
          - name: SONARQUBE_JDBC_URL
            value: {jdbc_url}
          - name: SONARQUBE_JDBC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
          resources:
            requests:
              cpu: 2
              memory: 2048Mi
            limits:
              cpu: 2
              memory: 4096Mi
          ports:
          - containerPort: 9000
            name: sonarqube
      volumes:
      - name: sonar-data
        persistentVolumeClaim:
          claimName: sonar-data
      - name: sonar-extensions
        persistentVolumeClaim:
          claimName: sonar-extensions
      terminationGracePeriodSeconds: 15
      initContainers:
      - name: fix-the-volume-permission
        image: busybox
        command:
        - sh
        - -c
        - chown -R 999:999 /opt/sonarqube/extensions
        securityContext:
          privileged: true
        volumeMounts:
        - name: sonar-extensions
          mountPath: /opt/sonarqube/extensions
      - name: fix-the-volume-permission1
        image: busybox
        command:
        - sh
        - -c
        - chown -R 999:999 /opt/sonarqube/data
        securityContext:
          privileged: true
        volumeMounts:
        - name: sonar-data
          mountPath: /opt/sonarqube/data
